services:
  postgres:
    image: postgres:16.0
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=secret_db
      - POSTGRES_USER=secret_user
      - POSTGRES_PASSWORD=secret_password